#!/usr/bin/env bash

echo -e "################# docker-login help #################"
echo -e "dbus-run-session -- bash\n"
echo -e "gnome-keyring-daemon --unlock\n"
echo -e "raspberry(Press ENTER)\n"
echo -e "# press CTRL+D"
echo -e "docker login\n"

dbus-run-session -- bash
gnome-keyring-daemon --unlock
raspberry
# press CTRL+D
docker login
